<!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="ie=edge"><meta name="theme-color" content="#000000"><title><?php    if(is_front_page())
       echo "Home";
   else if(is_404())
       echo "Page Not Found";
   else if(is_category() || is_search() )
       echo single_cat_title();
   else
       the_title();
   echo ' | '.get_bloginfo('name'); 
?></title><?php  //Template Name: Home
?><link rel="stylesheet" href="<?php echo get_stylesheet_directory_uri(); ?>/css/fonts/fonts.css"><link rel="stylesheet" href="<?php echo get_stylesheet_directory_uri(); ?>/css/app.css"><script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script><?php wp_head(); ?></head><body><?php include 'includes/mylottie.php'; ?>
<?php include 'includes/mymenu.php'; ?>
<?php include 'includes/myoverlay.php'; ?>
<?php include 'includes/mycanvas.php'; ?>
<?php include 'includes/myarchived.php'; ?>
<?php include 'includes/mygooey.php'; ?><div class="e-rel" id="barba-wrapper" data-barba="wrapper" data-scroll><div class="barba-container page-home e-wp" data-barba="container" data-barba-namespace="home" data-namespace="home" data-current="" data-scroll-content><div class="imgs-hidden e-hidden"><?php if(have_rows('folio_rpt','option')): while(have_rows('folio_rpt','option')) : the_row(); ?><img class="js-img img-load" src="<?php echo get_sub_field('image_project')['url']; ?>" alt="<?php echo get_sub_field('image_project')['alt']; ?>"><?php endwhile; else : endif; ?></div><div class="e-hold"><header class="header-home e-wp"><button class="header-home__welcome no-mobile e-rel e-curp hover-line scale"><div class="t-switch-gray e-rel wrap"><div class="wrapped">👋 Bienvenue</div><div class="line e-wp e-switch-gray e-switch"></div></div></button><div class="header-home__gif e-abs no-mobile"><img class="e-wp" src="<?php echo get_template_directory_uri(); ?>/images/seinfield.gif"></div><div class="header-home__title"><div class="hold-home"><h1 class="title-home t-switch pushoff wrap"><div class="wrapped">Digital</div></h1><h1 class="title-home t-switch wrap line2"><div class="wrapped">Designer &amp;</div></h1><h1 class="title-home t-switch wrap"><div class="wrapped">Storyteller</div></h1></div></div><div class="header-home__infos"><div class="header-home__infos__name"><h2 class="t-switch-gray wrap"><div class="wrapped">Jaslin Tonton</div></h2></div><div class="header-home__infos__role"><h2 class="t-switch-gray wrap"><div class="wrapped">Creative Director/Digital Designer</div></h2><h2 class="t-switch-gray wrap"><div class="wrapped"><?=date('Y') - 2012?>+ Years of Experience</div></h2></div><div class="header-home__infos__available"><h2 class="t-switch-gray wrap"><div class="wrapped">Available for Work</div></h2><script>user = 'hello';
site = 'hellotonton';
document.write('<div class="t-switch-gray wrap"><div class="wrapped"><a href=\"mailto:' + user + '@' + site + '.com\"><button class="t-switch-gray e-curp hover-line scale">');
document.write(user + '[at]' + site + '[dot]com<div class="line e-wp e-switch-gray e-switch"></div></button></a></div></div>');
</script></div></div></header><main class="main-home e-wp"><section class="about"><div class="hold-home scroll-about"><!-- img(src="https://dummyimage.com/271x294", alt="")--><video width="304" height="322" muted="true" loop="true" src="<?=get_template_directory_uri();?>/images/emoji-head.mp4"></video><div class="hold-p"><p class="t-switch about-header">Tonton. Name&rsquo;s so nice,</br> you say it twice.</p><p class="t-switch">I'm Jaslin (JAYs-lin) Tonton, an Orlando based Creative Director / Digital Designer with 9+ years of experience.</p><p class="t-switch"> For nearly a decade, I’ve helped inspire and direct creative teams toward idea-driven strategies, minimalism, and practical design.</p><p class="t-switch"> I’m open to new and exciting opportunities and would love to work with you.</p></div></div></section><section class="works"><div class="hold-home scroll-works"><h1 class="title-home t-switch wrap start-works"><div class="wrapped">Featured</div></h1><h1 class="title-home t-switch text-padding"><div class="wrapped">Work</div></h1><div class="links-folio" id="folio-ctn"><?php if(have_rows('folio_rpt','option')): while(have_rows('folio_rpt','option')) : the_row(); ?><div class="links-folio__each"><a href="<?php echo get_site_url(); ?>/<?php the_sub_field('url_project'); ?>" data-to="single" data-from="home" data-color="<?php the_sub_field('color_project'); ?>"><button class="e-curp hover-line"><h1 class="e-sans t-switch wrap"><div class="wrapped title-folio"><?php the_sub_field('title_project'); ?></div><div class="line-link e-wp e-switch"></div></h1></button></a></div><?php endwhile; else : endif; ?></div></div><div class="gap-black"></div></section></main></div><section class="awards e-wp"><div class="award__hold e-hold"><div class="hold-home"><div class="inline"><div class="awards__title start-awards"><h1 class="e-bold t-switch wrap"><div class="wrapped">Awards</div></h1><h1 class="e-bold t-switch wrap"><div class="wrapped">& Recognition</div></h1></div><div class="awards__fields"><div class="each-field"><div class="site"><div class="e-bold wrap"><div class="wrapped">Behance</div></div></div><div class="recog"><div class="t-switch-gray wrap"><div class="wrapped">Pantone</div></div><div class="t-switch-gray wrap"><div class="wrapped">Student Show</div></div></div></div><div class="each-field"><div class="site"><div class="e-bold t-switch-gray wrap"><div class="wrapped">Webby&rsquo;s</div></div></div><div class="recog"><div class="t-switch-gray wrap"><div class="wrapped">Tech Something</div></div></div></div></div></div></div></div></section><?php include 'includes/myfooter.php'; ?></div></div></body></html>